apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-proxy-config
  namespace: ingress-nginx
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      upstream backend {
        server wordpress-blue.ingress-nginx.svc.cluster.local:80 weight=50;
        server wordpress-green.ingress-nginx.svc.cluster.local:80 weight=50;
      }

      server {
        listen 80;
        location / {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

      }
    }

