apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: blue
  name: mysql-pv-claim-blue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: blue
  name: wordpress-pv-claim-blue
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
