apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blue
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      version: blue
  template:
    metadata:
      labels:
        app: wordpress
        version: blue
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_DATABASE
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-pv-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-pv-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim-blue

