apiVersion: v1
kind: Service
metadata:
  namespace: green
  name: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
    version: green
  type: ClusterIP
